server:
  port: 18080

spring:
  application:
    name: hq-training-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:hq_training}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwt:
    secret: "hq-training-sprint-day8-demo-secret-key-please-change-later-2026"
    expiration-hours: 8
